package clientetcp.resource;

public class RelatorioDialog extends javax.swing.JDialog {

	public RelatorioDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	public void setVisible(boolean value, String relatorio) {
		this.setVisible(value);
		textareaRelatorio.setText(relatorio);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	// GEN-BEGIN:initComponents
	private void initComponents() {

		dialogTitle = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jScrollPane1 = new javax.swing.JScrollPane();
		textareaRelatorio = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		dialogTitle.setText("Relatório");

		textareaRelatorio.setEditable(false);
		textareaRelatorio.setBackground(new java.awt.Color(255, 255, 255));
		textareaRelatorio.setColumns(20);
		textareaRelatorio.setRows(5);
		jScrollPane1.setViewportView(textareaRelatorio);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane1)
										.addGroup(layout.createSequentialGroup()
												.addComponent(dialogTitle)
												.addGap(0, 0, Short.MAX_VALUE)))
								.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(dialogTitle)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
								.addContainerGap()));

		pack();
	}//GEN-END:initComponents
	// </editor-fold>

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel dialogTitle;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextArea textareaRelatorio;
	// End of variables declaration//GEN-END:variables
}
